name: GL_proxy
description: "Proxy for GL"

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  app_links: 6.4.0
  crypto: 3.0.3
  flutter_dotenv: 5.2.1
  http: 1.2.2
  provider: 6.1.5
  url_launcher: 6.3.1
  flutter_launcher_icons: 0.14.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"